[project]
name = "content-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "raceychan", email = "raceychan@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
content-agents = "content_agents:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
